-- MySQL Script generated by MySQL Workbench
-- Sun Aug 31 15:02:33 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema employee
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema employee
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `employee` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `employee` ;

-- -----------------------------------------------------
-- Table `employee`.`department`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `employee`.`department` (
  `dept_no` CHAR(4) NOT NULL,
  `dept_name` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`dept_no`),
  UNIQUE INDEX `dept_name` (`dept_name` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `employee`.`employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `employee`.`employee` (
  `emp_no` INT NOT NULL,
  `birth_date` DATE NOT NULL,
  `first_name` VARCHAR(14) NOT NULL,
  `last_name` VARCHAR(16) NOT NULL,
  `gender` ENUM('M', 'F') NOT NULL,
  `hire_date` DATE NOT NULL,
  PRIMARY KEY (`emp_no`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `employee`.`dept_emp`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `employee`.`dept_emp` (
  `emp_no` INT NOT NULL,
  `dept_no` CHAR(4) NOT NULL,
  `from_date` DATE NOT NULL,
  `to_date` DATE NOT NULL,
  PRIMARY KEY (`emp_no`, `dept_no`),
  INDEX `dept_no` (`dept_no` ASC) VISIBLE,
  CONSTRAINT `dept_emp_ibfk_1`
    FOREIGN KEY (`emp_no`)
    REFERENCES `employee`.`employee` (`emp_no`)
    ON DELETE CASCADE,
  CONSTRAINT `dept_emp_ibfk_2`
    FOREIGN KEY (`dept_no`)
    REFERENCES `employee`.`department` (`dept_no`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `employee`.`dept_manager`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `employee`.`dept_manager` (
  `emp_no` INT NOT NULL,
  `dept_no` CHAR(4) NOT NULL,
  `from_date` DATE NOT NULL,
  `to_date` DATE NOT NULL,
  PRIMARY KEY (`emp_no`, `dept_no`),
  INDEX `dept_no` (`dept_no` ASC) VISIBLE,
  CONSTRAINT `dept_manager_ibfk_1`
    FOREIGN KEY (`emp_no`)
    REFERENCES `employee`.`employee` (`emp_no`)
    ON DELETE CASCADE,
  CONSTRAINT `dept_manager_ibfk_2`
    FOREIGN KEY (`dept_no`)
    REFERENCES `employee`.`department` (`dept_no`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `employee`.`salary`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `employee`.`salary` (
  `emp_no` INT NOT NULL,
  `amount` INT NOT NULL,
  `from_date` DATE NOT NULL,
  `to_date` DATE NOT NULL,
  PRIMARY KEY (`emp_no`, `from_date`),
  CONSTRAINT `salary_ibfk_1`
    FOREIGN KEY (`emp_no`)
    REFERENCES `employee`.`employee` (`emp_no`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `employee`.`title`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `employee`.`title` (
  `emp_no` INT NOT NULL,
  `title` VARCHAR(50) NOT NULL,
  `from_date` DATE NOT NULL,
  `to_date` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`emp_no`, `title`, `from_date`),
  CONSTRAINT `title_ibfk_1`
    FOREIGN KEY (`emp_no`)
    REFERENCES `employee`.`employee` (`emp_no`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

USE `employee` ;

-- -----------------------------------------------------
-- Placeholder table for view `employee`.`current_dept_emp`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `employee`.`current_dept_emp` (`emp_no` INT, `dept_no` INT, `from_date` INT, `to_date` INT);

-- -----------------------------------------------------
-- Placeholder table for view `employee`.`dept_emp_latest_date`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `employee`.`dept_emp_latest_date` (`emp_no` INT, `from_date` INT, `to_date` INT);

-- -----------------------------------------------------
-- View `employee`.`current_dept_emp`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `employee`.`current_dept_emp`;
USE `employee`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `employee`.`current_dept_emp` AS select `employee`.`l`.`emp_no` AS `emp_no`,`d`.`dept_no` AS `dept_no`,`employee`.`l`.`from_date` AS `from_date`,`employee`.`l`.`to_date` AS `to_date` from (`employee`.`dept_emp` `d` join `employee`.`dept_emp_latest_date` `l` on(((`d`.`emp_no` = `employee`.`l`.`emp_no`) and (`d`.`from_date` = `employee`.`l`.`from_date`) and (`employee`.`l`.`to_date` = `d`.`to_date`))));

-- -----------------------------------------------------
-- View `employee`.`dept_emp_latest_date`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `employee`.`dept_emp_latest_date`;
USE `employee`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `employee`.`dept_emp_latest_date` AS select `employee`.`dept_emp`.`emp_no` AS `emp_no`,max(`employee`.`dept_emp`.`from_date`) AS `from_date`,max(`employee`.`dept_emp`.`to_date`) AS `to_date` from `employee`.`dept_emp` group by `employee`.`dept_emp`.`emp_no`;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
